'use client';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../app/styles/Home.module.css';
import Confetti from './Confetti';
import { useState } from 'react';

const Home: NextPage = () => {
  const [isVisible, setIsVisible] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title> Confetti Button Example</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Confetti Button Example</h1>

        <div className={styles.grid}>
          <button onClick={() => setIsVisible(true)}>Fire</button>
          {isVisible && <Confetti />}
        </div>
      </main>

      <footer className={styles.footer}>
        <a href='/__repl' target='_blank' rel='noopener noreferrer'>
          Built on
          <span className={styles.logo}>
            <Image src='/replit.svg' alt='Replit Logo' width={20} height={18} />
          </span>
          Replit
        </a>
      </footer>
    </div>
  );
};

export default Home;
